locale: pt_BR

title: Auto Adrenalina
url: "https://www.autoadrenalina.com"
baseurl: ""
description: >-
  "Notícias automotivas, motos, supercarros, reviews completos, lançamentos e veículos elétricos. 
  Acompanhe tudo sobre o universo automotivo no Auto Adrenalina."

# theme: minima
email: thales.caricati@gmail.com
twitter_username: jekyllrb
github_username:  jekyll

permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap
