languages: ["pt", "en"]
default_lang: "pt"

title: Auto Adrenalina
url: "https://autoadrenalina.com"
baseurl: ""
description: >-
  "Sua revista automotiva Auto Adrenalina traz as últimas notícias automotivas sobre carros, motos, superesportivos, veículos elétricos, reviews, lançamentos e tecnologia automotiva em um local moderno e atualizado semanalmente."

email: thales.caricati@gmail.com

permalink: /:categories/:title/
markdown_ext: "md"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:categories/:title/
  posts_en:
    output: true
    permalink: /en/:categories/:title/

pagination:
  enabled: true
  per_page: 20
  sort_field: "date"
  sort_reverse: true
  permalink: "/pagina/:num/"
  title: ":title - página :num"
